<?php
    $movies = $this->renderMovies();
    $lastPage = $movies->page - 1;
    $currentPage = $movies->page;
    $nextPage = $movies->page + 1;
    $totalPage = $movies->total_pages;
    $movies = $movies->results;
?>
<style>
    .item.product.product-item {
        display: inline-block;
        margin: 15px 10px;
    }

    .item.product.product-item .product-item-info:hover{
        background: #fff;
        box-shadow: 3px 3px 4px 0 rgba(0,0,0,0.3);
        border: 1px solid #bbb;
        margin: -10px;
        padding: 9px;
        position: relative;
        z-index: 2;
    }

    .product.actions.product-item-actions {
        text-align: center;
        font-weight: bold;
        padding-bottom: 10px;

    }

    .product.actions.product-item-actions a{
        color: #FFF;
        text-decoration: none;
        padding: 10px 68px;
    }
    .add-product a{
        background-color: #ff0000b3;
    }

    .product-added a{
        background-color: #106f0ab0;
    }
</style>


<div class="page-main-actions container">

    <div class="admin__data-grid-header-row row row-gutter">
        <div class="col-xs-4">
            teste
        </div>
        <div class="col-xs-5">
            teste
        </div>
        <div class="col-xs-3">
            <div class="admin__data-grid-pager">
                <a href="<?= $this->getUrlBuilder("tmdb_movies/index/index", ['page' => $lastPage])?>" 
                   class="action-previous action-default" type="button" title="Previous Page" ></a>
                <label class="admin__control-support-text" ><?=$currentPage;?> of <?=$totalPage;?></label>
                <a href="<?= $this->getUrlBuilder("tmdb_movies/index/index", ['page' => $nextPage])?>" 
                   class="action-next action-default" type="button" title="Next Page" ></a>
            </div>
        </div>
    </div>
</div>
<div class="columns">
    <div class="colums main">
        <div class="products wrapper grid products-grid">
            <ol class="products list items product-items">
                <?php foreach ($movies as $movie): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                <img class="product-image-photo" 
                                     src="<?= $this->handleImageURI($movie->poster_path) ?>" 
                                     width="240" height="300" alt="<?= $movie->title ?>">
                            </span>
                        </span>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                   <h3 title="<?= $movie->title ?>"> <?= $this->sanitizeTitle($movie->title); ?> </h3>
                            </strong>
                            <div class="product actions product-item-actions">
                                <?php if (!$this->productAdded($movie->id)):?>
                                    <div class="actions-primary add-product">
                                            <a href="<?= $this->getUrlBuilder("tmdb_movies/product/index", ['movie_id' => $movie->id])?>" 
                                                    title="Add to Products" class="action tocart primary">
                                                    <span>Add to Products</span>
                                            </a>
                                    </div>
                                <?php else :?>
                                    <div class="actions-primary product-added">
                                            <a href="<?= $this->getUrlBuilder("catalog/product/edit", ['id' => $this->productAdded($movie->id)])?>" 
                                                title="Add to Products" class="action tocart primary">
                                                    <span>Product Added</span>
                                            </a>
                                    </div>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
</div>

